name:                daniell
version:             0.1.0.0
# github:              "hugodro/fudd/daniell"
license:             BSD3
author:              "Hugo DesRosiers"
maintainer:          "hugo.desrosiers@boardingcities.com"
copyright:           "Boarding Cities"

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/hugodrw/fudd/daniell>


dependencies:
  - aeson
  - base >= 4.7 && < 5
  - base-compat
  - bytestring
  # For CORS:
  - case-insensitive
  - containers
  - directory
  - either
  - exceptions
  - filepath
  - pathwalk
  - ginger >= 0.10.4.1
  - gitrev
  # For //, /: of http content types in accept HTML:
  - http-media
  # For JWT crypto support:
  - jose
  # For JWT crypto support:
  - lens
  - lucid
  # For syntax parsing:
  - megaparsec
  - parser-combinators
  # For Markdown content: 
  - mmark
  # For Ginger demo:
  - mtl
  - optparse-applicative
  - servant
  - servant-auth
  - servant-auth-server
  # For WebServer.Servant mkErrors:
  # - servant-errors
  - servant-multipart
  - servant-server
  - text
  - time
  - tomland >= 1.3.3.2
  - unix
  - unordered-containers
  - utf8-string
  # For TOML transformation into data structure:
  - validation-selective
  - vector
  - wai
  # For CORS:
  - wai-cors
  - wai-extra
  - warp
  - yaml
  - split
  # For CORS:
  - http-types
  # For testing http get:
  - http-client
  # For parsing programming languages:
  - tree-sitter
  - tree-sitter-haskell
  # For Compiler/Interpreter VM:
  - cryptohash-md5
  - array
  # For parsing TOML:
  - hashmap

default-extensions:
- OverloadedStrings
- DuplicateRecordFields
- OverloadedRecordDot

library:
  source-dirs: src

executables:
  daniell:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2  
    dependencies:
    - base
    - daniell

